version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/my-react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # SQLiteデータベースファイルを永続化するためのボリューム
      - ./backend/data:/app/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
